name: Push on Main

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Run unit tests
        run: python -m unittest discover -v -s tests -p 'test_unit_*.py'

  functional-tests:
    needs: unit-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Run functional tests
        run: python tests/test_functional_versioning.py
